export const POSTS_URL = process.env.REACT_APP_MY_URL + "postviewcreate/"
export const POST_URL = process.env.REACT_APP_MY_URL + "profile/"
export const LOGIN_URL = process.env.REACT_APP_MY_URL + "user/login/"
export const REGISTER_URL = process.env.REACT_APP_MY_URL + "user/register/"
export const LOGOUT_URL = process.env.REACT_APP_MY_URL + "user/logout/"
